package com.pong.pingpong;

import javafx.scene.paint.Color;
import javafx.scene.shape.Circle;

/**
 * Represents the ball object in the game.
 */
public class Ball {

    private double dx;
    private double dy;

    private double px;
    private double py;
    private double radius;
    private double speed;
    private Circle ball;

    /**
     * Constructs a new Ball object with the given center coordinates and radius (size).
     * The initial/default speed is set to 3.
     *
     * @param centerX the x-coordinate of the center of the ball
     * @param centerY the y-coordinate of the center of the ball
     * @param radius  the radius (size) of the ball
     */
    public Ball(double centerX, double centerY, double radius) {
        px = centerX;
        py = centerY;
        this.radius = radius;
        speed = 3;
        ball = new Circle(px, py, radius, Color.BLUE);
    }


    /**
     * Returns the JavaFX Circle shape representing the ball.
     *
     * @return the JavaFX Circle shape representing the ball
     */
    public Circle getBall() {
        return ball;
    }


    /**
     * Returns the current speed of the ball.
     *
     * @return the current speed of the ball
     */
    public double getSpeed() {
        return speed;
    }


    /**
     * Moves the ball by the specified change in x and y coordinates.
     *
     * @param dx the change in x coordinate
     * @param dy the change in y coordinate
     */
    public void move(double dx, double dy) {
        this.dy = getSpeed() * dy;
        this.dx = getSpeed() * dx;
        ball.setCenterX(ball.getCenterX() + this.dx);
        ball.setCenterY(ball.getCenterY() + this.dy);
    }


    /**
     * Increases the speed of the ball by 0.8, up to a maximum of 15.
     */
    public void speedUp() {
        if (speed < 15) {
            speed += 0.8;
        }
    }


    /**
     * Redraws the ball and makes it stop (speed = 0) in the serve position generated by the racquet methods.
     *
     * @param racquet the Racquet object to position the ball relative to
     */
    public void draw(Racquet racquet) {
        speed = 0;
        ball.setCenterX(racquet.ServeX());
        ball.setCenterY(racquet.ServeY());
    }


    /**
     * Sets the speed of the ball back to the default value of 3.
     */
    public void hurl() {
        speed = 3;
    }

}